/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package castissue

import spock.lang.Specification

class SomeTest extends Specification {
    def "test adult"() {
        when:
        def a = new Adult()
        def t = new Test(a)

        then:
        t.isMarried()
    }
    def "test person"() {
        when:
        def p = new Person()
        def t = new Test(p)

        then:
        !t.isMarried()
    }
}
